name: Docker Build and Deploy!!
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: sirpi/sampleR:v1
        
    - name: Deploy to Local Server via SSH
      run: |
        # Setup SSH key
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/ssh_private_key
        chmod 600 /tmp/ssh_private_key
        
        # Deploy using SSH
        ssh -o StrictHostKeyChecking=no -i /tmp/ssh_private_key -p ${{ secrets.SERVER_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} '
          # Log in to DockerHub
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
          
          # Stop and remove existing container (if running)
          if [ "$(docker ps -q --filter name= groundwater)" ]; then
            docker stop sampleR || true
            docker rm  sampleR  || true
          fi
          
          # Pull the latest Docker image
          docker pull sirpi/sampleR:v1
          
          # Run the container
          docker run -d \
            --restart=unless-stopped \
            --name sampleR \
            -p 3838:3838 \
            sirpi/sampleR:v1
        '
        
    - name: Remove SSH key
      if: always()
      run: rm -f /tmp/ssh_private_key
