name: Docker Build and Deploy!!

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: sirpi/sampler:v1

    - name: Deploy to Local Server via SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/ssh_private_key
        chmod 600 /tmp/ssh_private_key

        ssh -o StrictHostKeyChecking=no -i /tmp/ssh_private_key -p ${{ secrets.SERVER_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          docker stop sampler || true
          docker rm sampler || true

          docker pull sirpi/sampler:v1

          docker run -d \
            --restart=unless-stopped \
            --name sampler \
            -p 4001:3838 \
            sirpi/sampler:v1

          docker ps | grep sampler
        EOF

    - name: Remove SSH key
      if: always()
      run: rm -f /tmp/ssh_private_key
