name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Copy Files to Remote Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key

        # Use rsync to transfer the code
        rsync -avz -e "ssh -i private_key -p $SERVER_PORT -o StrictHostKeyChecking=no" ./ $SERVER_USER@$SERVER_IP:~/todo-app

    - name: SSH and Deploy on Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key

        ssh -o StrictHostKeyChecking=no -p $SERVER_PORT -i private_key $SERVER_USER@$SERVER_IP << EOF
          cd ~/todo-app

          # Stop and remove existing container
          docker stop piperplot || true
          docker rm piperplot || true

          # Build and run the Docker container locally
          docker build -t piperplot:latest .
          docker run -d --name piperplot -p 4001:3838 piperplot:latest

          # Confirm it’s running
          sleep 5
          docker ps | grep todo_run
        EOF
